apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-khqsofti
  janus-idp.io/tekton: go-khqsofti
  backstage.io/kubernetes-id: go-khqsofti
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-khqsofti
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
